#version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"
  api1: &api
    build: .
    hostname: api1
    environment:
      - REDIS_URL=redis:6379
      - HTTP_PORT=8080
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKERS_COUNT=25 //40
      - RETRY_DEFAULT=2
      - HTTP_DEFAULT_TIMEOUT=3
      - HTTP_FALLBACK_TIMEOUT=2
      - CONSECUTIVE_FAILURES_DEFAULT=2
      - CONSECUTIVE_FAILURES_FALLBACK=1
      - CIRCUIT_BREAKER_INTERVAL_DEFAULT=500
      - CIRCUIT_BREAKER_INTERVAL_FALLBACK=500
      - CIRCUIT_BREAKER_TIMEOUT_DEFAULT=4
      - CIRCUIT_BREAKER_TIMEOUT_FALLBACK=2
    networks:
      - rinha-net
      - payment-processor-net
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "130MB"
    depends_on:
      redis:
        condition: service_healthy
  api2:
    <<: *api
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "130MB"
  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 50000  --tcp-keepalive 60
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "30MB"

#--- NETWORKS ---
networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true
